# Введение
Преобразование Фурье является достаточно популярным и хорошо изученным инструментом в сфере обработки сигналов и анализа временных рядов.
Публикация работы Блэкмэна (Blackman) и Туки (Tukey) "Измерение энергетического спектра (The measurment of power spectra)"[@blacktukey], а так же Кули (Coley) и Tуки (Tuckey) "Алгоритм машинного вычисления сложных рядов Фурье (An algorithm of machine computation of complex Fourier series)" [@cooltukey] привели к значительным успехам в сфере спектрального анализа временных рядов.

При этом данная методика в некоторых случаях обладает явными недостатками. Сигнал $x(t)$[^or-series] содержит полную информацию во временном пространстве, то есть амплитуду сигнала в каждый фиксированный момент времени $t_0$. Однако, из $x(t)$ невозможно напрямую получить информацию описывающую частотную характеристику сигнала. С другой стороны, разложение $X(f)$ полученное с помощью преобразовнаия Фурье сингнала $x(t)$ содержит в себе всю информацию о сигнале в частотном пространстве: магнитуду и фазовый угол каждой частотной компоненты $f$. Но теперь, нет ни какой информации о том где конкретно во времени та или иная частота появилась. Иными словами ни $x(t)$, ни $X(f)$ не дают полного описания сигнала.

[^or-series]:
  Здесь и далее мы не будем делать явного различия между понятиями *сигнал* и *временной ряд*, если не оговрено обратное

Чтобы разрешить эту проблему, мы можем использовать оконное преобразование Фурье, т.е. обрезать сигнал $x(t)$ временным окном $\omega(t - \tau)$:
\begin{equation}
    x'(t) = \omega(t - \tau) x(t),
\end{equation}

где само окно имеет ширину $T$ и может смещаться во времени с изменением параметра $\tau$:
\begin{equation}
    \omega(t) =
    \begin{cases}
        1, t \in [0, T] \\
        0, t \not\in [0, T]
    \end{cases}
\end{equation}

Так мы получим разложение сигнала лишь для определенного периода $T$. Недостатком такого преобразования является сильное искажение в частотном пространстве, вызванное резким обрезанием сигнала вне окна. Чтобы уменьшить это искажение, прямоугольное окно может быть заменено более гладким Гауссовским окном с постепенным спадом:
\begin{equation} x'(t) = g(t) x(t), ~ g(t) = c \exp{((t - \tau)^2 / \sigma ^ 2)}\end{equation}

С другой стороны, мы можем считать что обрезанный сигнал $x(t)$ повторяется во времени с конечным периодном $T$. В этом случае, разложение становится дискретным, содержащим конечное число чатотных компонент $X[k]~(k = 0, \pm 1, \pm 2, \dots)$  для дискретных частот $f = kf_0 =  k/ T$. В таком случае информация о любой частоте в промежутке между $X[k]$ и $X[k + 1]$ потеряна. Более того, чем большую детализацию мы получаем во временном пространстве уменьшая $T$, тем меньшую детализацию в частотном пространстве мы получаем из-за увеличаения промежутков $f_0 = 1 / T$ между частотными компонентами.

Мы видим, что просто невозможно получить полную информацию о сигнале сразу во временном и частотном пространствах, так как увеличивая детатлизацию в одном пространстве мы автоматически уменьшаем ее в другом.

Если характеристики сигнала меняются с течением времени незначительно, то есть сигнал стационарен, тогда преобрзавование Фурье подходит для анализа. Однаком, во многих приложениях сигнал быстроменяющийся или нестационарный(например есть тренд или резкие скачки). В этих случаях анализ с помощью преобразования Фурье неспособен определить где или когда эти изменения имели место.

С целью преодолеть недостатки этого метода и получить необходимую информацию сразу во временном и частотном пространствах, используется другое преобразование, названное __вейвлет-преобразованием__.
